### ISSUE TITLE
When a user signs in, they are directed to the "authorized_applications" route, which has no "New Application" button

### ISSUE THREAD

**Issue by nellshamrell** [chef/oc-id#54] opened 2015-04-10 20:48 UTC
As a user
When I sign into oc-id
I am redirected to the authorized_applications index page
And there is no "New Application" button

To access a page with the new application button, a user needs to manually change the url to /applications, rather than /authorized_applications.  It's pretty confusing when someone is following a tutorial or instructions that say to make a new application once they are signed in, as mentioned in #53. 

It would be ideal to either have the button available on the [authorized_applications index page](https://github.com/chef/oc-id/blob/5958cb34086795f5e726487840aa8ea0838685c6/app/views/doorkeeper/authorized_applications/index.html.erb) or have the [home controller index method](https://github.com/chef/oc-id/blob/e48a848cf66044c7301710aec147cae9994ef6a7/app/controllers/home_controller.rb#L4) redirect to the applications path, rather than authorized_applications path.

**Comment by smith** [comment] 2015-04-13 18:16
Closing this as a duplicate of #18. It doesn't really make sense to have a user add authorized applications, as applications ask the user to authorize them.

We pretty much are going for copying GitHub on this, so check out https://github.com/settings/applications to see something that looks very similar to the end state we want for oc-id.

**Closed by smith** 2015-04-13 18:16 UTC
